import { AddSpec, SaveSpec , LoadSpec} from "explorer_window_controls.slint";
import { HorizontalBox } from "std-widgets.slint";
component ExplorerItem inherits Rectangle {
    
}

component ExplorerItemROI inherits Rectangle {
    
}

component ExplorerControls inherits Rectangle {
    y: 0;
    height: 5%;
    padding-top: 0px;
}
export component Explorer inherits Rectangle {
    property <color> bg: #d4cece;
    width: 17%;
    background: bg;
    ExplorerControls {
        background: parent.background.darker(0.1);
        HorizontalBox {
            height: 70%;
            padding-top: 0;
            //padding-bottom: (parent.height - self.height)/2;
            padding-right: parent.width*0.01;
            alignment: end;
            vertical-stretch: 1;
            SaveSpec {
                height: parent.height;
                padding: 0px;
                background: bg.darker(0.1);
            }
            LoadSpec {
                height: parent.height;
                padding: 0px;
                background: bg.darker(0.1);
            }
            AddSpec {
                height: parent.height;
                padding: 0px;
                background: bg.darker(0.1);
            }
        }
    }

}